### ISSUE TITLE
Python Support

### ISSUE THREAD

**Issue by donatoaguirre24** [perragnar/september-steel#1]
First of all congratulations, **the theme looks awesome**. It would be great if you could add support for Python 3 with a syntax highlight similar to the one provided by the Dracula theme.

**Comment by perragnar** [comment]
Thanks for the feedback. I will take a look at Dracula theme and see if I can come up with something similar adjusted to September Steel.

**Comment by perragnar** [comment]
@donatoaguirre24 I don't write any python myself. Is the current colors way off or do you want just minor tweaks?

**Comment by donatoaguirre24** [comment]
I think what is mainly missing is highlighting in the methods and the call to functions, the colors seem to be good for everything else. Then I leave two images as a comparison to show what I mean.

Dracula Official: 
![image](https://user-images.githubusercontent.com/20030075/33032606-7b821a44-ce00-11e7-8e80-88b2f0043c7d.png)

![image](https://user-images.githubusercontent.com/20030075/33033086-ffbbc05c-ce01-11e7-880e-f9a858e8fcc8.png)


September Steel:
![image](https://user-images.githubusercontent.com/20030075/33033194-5c92f052-ce02-11e7-9e87-4faf2e71c63e.png)

![image](https://user-images.githubusercontent.com/20030075/33033105-0d6273f4-ce02-11e7-9781-30c70c685189.png)

**Comment by perragnar** [comment]
Alright! What do you think about this? 

![Python 3](https://www.evernote.com/l/AHrnk26hDR5OHrIInl3ETUB9df-4bT18mkYB/image.png)

**Comment by donatoaguirre24** [comment]
It looks really cool. Thank you very much, excellent job.

**Comment by perragnar** [comment]
A new version is heading for the market. It shouldn't take long until you can update.
Take it for a spin and let me know if it runs OK with your code.

**Comment by donatoaguirre24** [comment]
The update just arrived, I looked at it and everything looks very good. Thanks for listening
